-- 011: Daily Words table
-- Stores daily AI terminology explanations generated by MiniMax
-- Content is refreshed every 15 days via CRON

CREATE TABLE IF NOT EXISTS daily_words (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  term          TEXT NOT NULL,
  content       TEXT NOT NULL,
  provider      TEXT,
  display_date  DATE NOT NULL,
  generated_at  TIMESTAMPTZ DEFAULT now(),
  cycle_id      INT NOT NULL DEFAULT 1,
  UNIQUE(term, cycle_id)
);

-- Fast lookup by date
CREATE INDEX IF NOT EXISTS idx_daily_words_display_date ON daily_words (display_date DESC);

-- Row-Level Security
ALTER TABLE daily_words ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "daily_words_public_read" ON daily_words
  FOR SELECT USING (true);

-- Write access restricted to service role
CREATE POLICY "daily_words_service_write" ON daily_words
  FOR ALL USING (auth.role() = 'service_role');
